version: "3"

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8030:80
    working_dir: /srv/web
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/web
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /srv/web
    volumes:
      - ./:/srv/web
      - /.composer:/.composer
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /srv/web
    volumes:
      - ./:/srv/web
      - /.npm:/.npm
    command: npm run dev
    ports:
      - 8080:8080
